package cn.boom.mywebsite.mapper;

import cn.boom.mywebsite.pojo.TbAdmin;
import cn.boom.mywebsite.pojo.TbAdminExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TbAdminMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_admin
     *
     * @mbggenerated
     */
    int countByExample(TbAdminExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_admin
     *
     * @mbggenerated
     */
    int deleteByExample(TbAdminExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_admin
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_admin
     *
     * @mbggenerated
     */
    int insert(TbAdmin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_admin
     *
     * @mbggenerated
     */
    int insertSelective(TbAdmin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_admin
     *
     * @mbggenerated
     */
    List<TbAdmin> selectByExample(TbAdminExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_admin
     *
     * @mbggenerated
     */
    TbAdmin selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_admin
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") TbAdmin record, @Param("example") TbAdminExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_admin
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") TbAdmin record, @Param("example") TbAdminExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_admin
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TbAdmin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_admin
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TbAdmin record);
}