package cn.boom.mywebsite.mapper;

import cn.boom.mywebsite.pojo.TbBlogCategory;
import cn.boom.mywebsite.pojo.TbBlogCategoryExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TbBlogCategoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_blog_category
     *
     * @mbggenerated
     */
    int countByExample(TbBlogCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_blog_category
     *
     * @mbggenerated
     */
    int deleteByExample(TbBlogCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_blog_category
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_blog_category
     *
     * @mbggenerated
     */
    int insert(TbBlogCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_blog_category
     *
     * @mbggenerated
     */
    int insertSelective(TbBlogCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_blog_category
     *
     * @mbggenerated
     */
    List<TbBlogCategory> selectByExample(TbBlogCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_blog_category
     *
     * @mbggenerated
     */
    TbBlogCategory selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_blog_category
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") TbBlogCategory record, @Param("example") TbBlogCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_blog_category
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") TbBlogCategory record, @Param("example") TbBlogCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_blog_category
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TbBlogCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_blog_category
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TbBlogCategory record);
}