package cn.boom.mywebsite.mapper;

import cn.boom.mywebsite.pojo.TbTrends;
import cn.boom.mywebsite.pojo.TbTrendsExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TbTrendsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_trends
     *
     * @mbggenerated
     */
    int countByExample(TbTrendsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_trends
     *
     * @mbggenerated
     */
    int deleteByExample(TbTrendsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_trends
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_trends
     *
     * @mbggenerated
     */
    int insert(TbTrends record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_trends
     *
     * @mbggenerated
     */
    int insertSelective(TbTrends record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_trends
     *
     * @mbggenerated
     */
    List<TbTrends> selectByExample(TbTrendsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_trends
     *
     * @mbggenerated
     */
    TbTrends selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_trends
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") TbTrends record, @Param("example") TbTrendsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_trends
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") TbTrends record, @Param("example") TbTrendsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_trends
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TbTrends record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_trends
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TbTrends record);
}