package xyz.lirui123.mywebsite.pojo;

import java.io.Serializable;
import java.util.Date;

public class TbComment implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_comment.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_comment.type
     *
     * @mbggenerated
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_comment.blog_id
     *
     * @mbggenerated
     */
    private Long blogId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_comment.trends_id
     *
     * @mbggenerated
     */
    private Long trendsId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_comment.content
     *
     * @mbggenerated
     */
    private String content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_comment.uid
     *
     * @mbggenerated
     */
    private Long uid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_comment.to_cid
     *
     * @mbggenerated
     */
    private Long toCid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_comment.prase_count
     *
     * @mbggenerated
     */
    private Long praseCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_comment.reply_count
     *
     * @mbggenerated
     */
    private Long replyCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_comment.created
     *
     * @mbggenerated
     */
    private Date created;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_comment.status
     *
     * @mbggenerated
     */
    private String status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_comment.id
     *
     * @return the value of tb_comment.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_comment.id
     *
     * @param id the value for tb_comment.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_comment.type
     *
     * @return the value of tb_comment.type
     *
     * @mbggenerated
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_comment.type
     *
     * @param type the value for tb_comment.type
     *
     * @mbggenerated
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_comment.blog_id
     *
     * @return the value of tb_comment.blog_id
     *
     * @mbggenerated
     */
    public Long getBlogId() {
        return blogId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_comment.blog_id
     *
     * @param blogId the value for tb_comment.blog_id
     *
     * @mbggenerated
     */
    public void setBlogId(Long blogId) {
        this.blogId = blogId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_comment.trends_id
     *
     * @return the value of tb_comment.trends_id
     *
     * @mbggenerated
     */
    public Long getTrendsId() {
        return trendsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_comment.trends_id
     *
     * @param trendsId the value for tb_comment.trends_id
     *
     * @mbggenerated
     */
    public void setTrendsId(Long trendsId) {
        this.trendsId = trendsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_comment.content
     *
     * @return the value of tb_comment.content
     *
     * @mbggenerated
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_comment.content
     *
     * @param content the value for tb_comment.content
     *
     * @mbggenerated
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_comment.uid
     *
     * @return the value of tb_comment.uid
     *
     * @mbggenerated
     */
    public Long getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_comment.uid
     *
     * @param uid the value for tb_comment.uid
     *
     * @mbggenerated
     */
    public void setUid(Long uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_comment.to_cid
     *
     * @return the value of tb_comment.to_cid
     *
     * @mbggenerated
     */
    public Long getToCid() {
        return toCid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_comment.to_cid
     *
     * @param toCid the value for tb_comment.to_cid
     *
     * @mbggenerated
     */
    public void setToCid(Long toCid) {
        this.toCid = toCid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_comment.prase_count
     *
     * @return the value of tb_comment.prase_count
     *
     * @mbggenerated
     */
    public Long getPraseCount() {
        return praseCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_comment.prase_count
     *
     * @param praseCount the value for tb_comment.prase_count
     *
     * @mbggenerated
     */
    public void setPraseCount(Long praseCount) {
        this.praseCount = praseCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_comment.reply_count
     *
     * @return the value of tb_comment.reply_count
     *
     * @mbggenerated
     */
    public Long getReplyCount() {
        return replyCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_comment.reply_count
     *
     * @param replyCount the value for tb_comment.reply_count
     *
     * @mbggenerated
     */
    public void setReplyCount(Long replyCount) {
        this.replyCount = replyCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_comment.created
     *
     * @return the value of tb_comment.created
     *
     * @mbggenerated
     */
    public Date getCreated() {
        return created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_comment.created
     *
     * @param created the value for tb_comment.created
     *
     * @mbggenerated
     */
    public void setCreated(Date created) {
        this.created = created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_comment.status
     *
     * @return the value of tb_comment.status
     *
     * @mbggenerated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_comment.status
     *
     * @param status the value for tb_comment.status
     *
     * @mbggenerated
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }
}