package xyz.lirui123.mywebsite.protal.mapper;

import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Component;
import xyz.lirui123.mywebsite.pojo.TbBlog;
import xyz.lirui123.mywebsite.pojo.TbBlogExample;

import java.util.List;


@Component
public interface TbBlogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_blog
     *
     * @mbggenerated
     */
    int countByExample(TbBlogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_blog
     *
     * @mbggenerated
     */
    int deleteByExample(TbBlogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_blog
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_blog
     *
     * @mbggenerated
     */
    int insert(TbBlog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_blog
     *
     * @mbggenerated
     */
    int insertSelective(TbBlog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_blog
     *
     * @mbggenerated
     */
    List<TbBlog> selectByExample(TbBlogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_blog
     *
     * @mbggenerated
     */
    TbBlog selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_blog
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") TbBlog record, @Param("example") TbBlogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_blog
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") TbBlog record, @Param("example") TbBlogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_blog
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TbBlog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_blog
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TbBlog record);
}